version: '3'

services:
  reverse-proxy:
    # The official v2.0 Traefik docker image
    image: traefik:latest
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker --api.dashboard=true
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


  poster-server:
    image: samuelbeckinghamcook/acpm-server
    ports:
      - "8001:80"
    labels:
      - "traefik.http.routers.poster-server.rule=Host(`acpostermaker.com`) && PathPrefix(`/api/`)"

  poster-frontend:
    image: samuelbeckinghamcook/acpm-frontend
    labels:
      - "traefik.http.routers.poster-frontend.rule=Host(`acpostermaker.com`)"
