# https://hub.docker.com/_/microsoft-dotnet-core
FROM mcr.microsoft.com/dotnet/core/sdk:3.1 AS build
RUN apt-get update \
        && echo 'msttcorefonts msttcorefonts/accepted-mscorefonts-eula select true' | debconf-set-selections \
        && apt-get install -y --allow-unauthenticated \
        ttf-mscorefonts-installer*
WORKDIR /source

# copy csproj and restore as distinct layers
COPY *.sln .
COPY ACPosterMaker.Server/*.csproj ./ACPosterMaker.Server/
RUN dotnet restore

# copy everything else and build app
COPY ACPosterMaker.Server/. ./ACPosterMaker.Server/
WORKDIR /source/ACPosterMaker.Server
RUN dotnet publish -c release -o /app

# final stage/image
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1
RUN apt-get update \
        && echo 'msttcorefonts msttcorefonts/accepted-mscorefonts-eula select true' | debconf-set-selections \
        && apt-get install -y --allow-unauthenticated \
        ttf-mscorefonts-installer*
WORKDIR /app
COPY --from=build /app ./
ENTRYPOINT ["dotnet", "ACPosterMaker.Server.dll"]
